# Generated by Django 2.2 on 2019-09-04 15:01

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Make: ')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('yearOfСarManufacture', models.DateTimeField(blank=True, verbose_name='Year Of Сar Manufacture')),
                ('vin', models.IntegerField(blank=True, verbose_name='VIN')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='First name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last name')),
                ('birthDate', models.DateTimeField(verbose_name='Date of birth')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('isReturn', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(blank=True, verbose_name='Date of order')),
                ('orderAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Order Amount')),
                ('orderStatus', models.CharField(choices=[('cancelled', 'Cancelled'), ('progress', ' In Progress'), ('completed', 'Completed')], default='progress', max_length=100, verbose_name='Order status')),
                ('orderCar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Car')),
                ('orderOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Customer'),
        ),
    ]
