# Generated by Django 2.2 on 2019-09-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Make ')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('yearOfСarManufacture', models.DateTimeField(blank=True, verbose_name='Year Of Сar Manufacture')),
                ('vin', models.IntegerField(verbose_name='VIN')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='First name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last name')),
                ('birthDate', models.DateTimeField(verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', ' Female')], default='M', max_length=100, verbose_name='Sex')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('isReturn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(verbose_name='Date of order')),
                ('orderAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Amount')),
                ('orderStatus', models.CharField(choices=[('cancelled', 'Cancelled'), ('progress', ' In Progress'), ('completed', 'Completed')], default='progress', max_length=100, verbose_name='Order status')),
                ('orderCar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainPage.Car')),
                ('orderOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainPage.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Customer'),
        ),
    ]
