# Generated by Django 2.2 on 2019-09-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='isReturn',
            field=models.BooleanField(default=False),
        ),
    ]
