# Generated by Django 2.2 on 2019-09-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20190906_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('progress', ' In Progress'), ('completed', 'Completed')], default='progress', max_length=20, verbose_name='Order status'),
        ),
    ]
