# Generated by Django 2.2 on 2019-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20190904_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthDate',
            field=models.DateTimeField(verbose_name='Date of birth(d/m/y)'),
        ),
    ]
