# Generated by Django 2.2 on 2019-09-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20190922_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=18, unique=True, verbose_name='VIN'),
        ),
    ]
