# Generated by Django 2.2 on 2019-09-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20190904_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make '),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.IntegerField(verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthDate',
            field=models.DateTimeField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(verbose_name='Date of order'),
        ),
    ]
