# Generated by Django 2.2 on 2019-09-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20190906_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='yearOfСarManufacture',
            field=models.DateField(blank=True, verbose_name='Year Of Сar Manufacture'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthDate',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
