# Generated by Django 2.2 on 2019-09-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_auto_20190905_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainPage.Customer'),
        ),
    ]
